defmodule Exograph.Extractor.ExAST do
  @moduledoc """
  Extracts ExAST-backed structural fragments from Elixir source files.
  """

  alias ExDNA.AST.Fingerprint
  alias Exograph.{Fragment, Package, PackageVersion}
  alias Exograph.File, as: SourceFile

  @default_opts [min_mass: 15, literal_mode: :keep, normalize_pipes: true]

  def index_paths(paths, opts \\ []) do
    paths
    |> stream_paths(opts)
    |> Enum.to_list()
  end

  def stream_paths(paths, opts \\ []) do
    paths
    |> List.wrap()
    |> Enum.flat_map(&expand_path/1)
    |> Enum.uniq()
    |> Enum.sort()
    |> Task.async_stream(&index_file(&1, opts),
      max_concurrency: Keyword.get(opts, :index_concurrency, System.schedulers_online()),
      ordered: false,
      timeout: :infinity
    )
    |> Stream.flat_map(fn
      {:ok, fragments} -> fragments
      {:exit, _reason} -> []
    end)
  end

  def stream_sources(sources, opts \\ []) do
    sources
    |> Task.async_stream(fn {path, source} -> index_source(path, source, opts) end,
      max_concurrency: Keyword.get(opts, :index_concurrency, System.schedulers_online()),
      ordered: false,
      timeout: :infinity
    )
    |> Stream.flat_map(fn
      {:ok, fragments} -> fragments
      {:exit, _reason} -> []
    end)
  end

  @spec index_file(String.t(), keyword()) :: [Fragment.t()]
  def index_file(file, opts \\ []) do
    case File.read(file) do
      {:ok, source} -> index_source(file, source, opts)
      _ -> []
    end
  end

  def index_source(file, source, opts \\ []) do
    opts = Keyword.merge(@default_opts, opts)

    with {:ok, ast} <- Exograph.ElixirParser.string_to_quoted(source, parser_opts(file, opts)) do
      package_context = package_context(opts)
      source_file = SourceFile.new(file, source, package_context)

      ast = neutralize_atom_word_sigils(ast)
      modules = collect_modules(ast)

      min_mass = effective_min_mass(file, source, opts)

      ast
      |> Fingerprint.fragments(file, min_mass, opts)
      |> Enum.map(&to_fragment(&1, source_file, package_context, modules))
      |> compute_end_lines()
    else
      _ -> []
    end
  end

  defp to_fragment(fingerprint, source_file, package_context, modules) do
    ast = fingerprint.ast
    {kind, name, arity} = classify(ast)
    line = Map.get(fingerprint, :line, line(ast))
    exact_hash = fingerprint.hash
    terms = ExAST.Index.Terms.from_ast(ast)

    content_hash =
      compute_content_hash(package_context.package_version_id, fingerprint.file, line, exact_hash)

    %Fragment{
      id: nil,
      content_hash: content_hash,
      file: fingerprint.file,
      source: source_file.source,
      package_id: package_context.package_id,
      package_version_id: package_context.package_version_id,
      file_id: nil,
      ast: ast,
      kind: kind,
      module: containing_module(modules, line),
      name: name,
      arity: arity,
      line: line,
      mass: fingerprint.mass,
      exact_hash: exact_hash,
      terms: terms,
      sub_hashes: fingerprint.sub_hashes
    }
  end

  defp parser_opts(file, opts) do
    [
      line: 1,
      columns: true,
      token_metadata: true,
      file: file,
      emit_warnings: false
    ]
    |> put_optional(:static_atoms, Keyword.get(opts, :static_atoms))
  end

  defp put_optional(opts, _key, nil), do: opts
  defp put_optional(opts, key, value), do: Keyword.put(opts, key, value)

  defp effective_min_mass(file, source, opts) do
    min_mass = Keyword.fetch!(opts, :min_mass)
    generated_min_mass = Keyword.get(opts, :generated_min_mass)

    if is_integer(generated_min_mass) and generated_source?(file, source) do
      max(min_mass, generated_min_mass)
    else
      min_mass
    end
  end

  defp generated_source?(file, source) do
    generated_path?(file) or generated_comment?(source)
  end

  defp generated_path?(file) do
    file
    |> Path.split()
    |> Enum.any?(&(&1 in ["generated", "gen"]))
  end

  defp generated_comment?(source) do
    source
    |> String.slice(0, 2_000)
    |> String.downcase()
    |> String.contains?(["generated", "do not edit", "autogenerated", "auto-generated"])
  end

  defp neutralize_atom_word_sigils(ast) do
    Macro.prewalk(ast, fn
      {:sigil_w, meta, [content, modifiers]} when modifiers in [[?a], ~c"a"] ->
        {:sigil_w, meta, [content, []]}

      {:sigil_W, meta, [content, modifiers]} when modifiers in [[?a], ~c"a"] ->
        {:sigil_W, meta, [content, []]}

      node ->
        node
    end)
  end

  defp collect_modules(ast) do
    {_ast, modules} =
      Macro.prewalk(ast, [], fn
        {:defmodule, meta, [{:__aliases__, _, parts} | _]} = node, acc when is_list(meta) ->
          if Enum.all?(parts, &is_atom/1) do
            line = Keyword.get(meta, :line, 0)
            end_line = Keyword.get(meta, :end, []) |> Keyword.get(:line, 999_999)
            {node, [{Enum.join(parts, "."), line, end_line} | acc]}
          else
            {node, acc}
          end

        node, acc ->
          {node, acc}
      end)

    Enum.sort_by(modules, fn {_name, line, _end_line} -> line end)
  end

  defp containing_module(modules, line) do
    modules
    |> Enum.filter(fn {_name, mod_line, mod_end} -> line > mod_line and line <= mod_end end)
    |> List.last()
    |> case do
      {name, _, _} -> name
      nil -> nil
    end
  end

  @function_kinds [:def, :defp, :defmacro, :defmacrop]

  defp compute_end_lines(fragments) do
    function_lines =
      fragments
      |> Enum.filter(&(&1.kind in @function_kinds))
      |> Enum.map(& &1.line)
      |> Enum.sort()

    Enum.map(fragments, fn fragment ->
      if fragment.kind in @function_kinds do
        next_line =
          Enum.find(function_lines, fn l -> l > fragment.line end)

        %{fragment | end_line: if(next_line, do: next_line - 1, else: 999_999)}
      else
        fragment
      end
    end)
  end

  defp classify({form, _meta, [head | _]}) when form in [:def, :defp, :defmacro, :defmacrop] do
    case unwrap_head(head) do
      {name, _, nil} when is_atom(name) ->
        {form, Atom.to_string(name), 0}

      {name, _, args} when is_atom(name) and is_list(args) ->
        {form, Atom.to_string(name), length(args)}

      _ ->
        {form, nil, nil}
    end
  end

  defp classify({:defmodule, _meta, [module_ast | _]}) do
    {:module, alias_name(module_ast), nil}
  end

  defp classify(_ast), do: {:expression, nil, nil}

  defp unwrap_head({:when, _, [head | _]}), do: unwrap_head(head)
  defp unwrap_head(head), do: head

  defp alias_name({:__aliases__, _, parts}) do
    if Enum.all?(parts, &is_atom/1), do: Enum.join(parts, "."), else: nil
  end

  defp alias_name(_), do: nil

  defp line({_form, meta, _args}), do: Keyword.get(meta, :line, 0)
  defp line(_), do: 0

  defp package_context(opts) do
    cond do
      version_attrs = Keyword.get(opts, :package_version) ->
        version = PackageVersion.new(version_attrs)

        %{
          package_id: version.package_id,
          package_version_id: version.id
        }

      package_attrs = Keyword.get(opts, :package) ->
        package = Package.new(package_attrs)

        %{
          package_id: package.id,
          package_version_id: nil
        }

      true ->
        %{
          package_id: nil,
          package_version_id: nil
        }
    end
  end

  defp compute_content_hash(package_version_id, file, line, hash) do
    :crypto.hash(:sha256, :erlang.term_to_binary({package_version_id, file, line, hash}))
  end

  defp expand_path(path) do
    cond do
      File.dir?(path) -> Path.wildcard(Path.join(path, "**/*.{ex,exs}"))
      String.contains?(path, "*") -> Path.wildcard(path)
      File.regular?(path) -> [path]
      true -> []
    end
  end
end
