defmodule Mix.Tasks.Exograph.Reach.Audit do
  @moduledoc """
  Audits Reach source-pattern smell modules against an Exograph DuckDB index.

      mix exograph.reach.audit Reach.Smell.Checks.PipelineWaste \
        --duckdb-database /tmp/exograph-prod-shard-bench/hex_0.duckdb \
        --prefix hex_0 \
        --limit 50

  Each positional argument is a Reach smell module name. The module is loaded at
  runtime and must expose `__reach_pattern_check__/0`, which is generated by
  `Reach.Smell.Check.Source`.

  ## Options

    * `--repo` - Ecto repo module for a QuackDB-backed DuckDB repo
    * `--prefix` - Exograph table prefix (default: `exograph`)
    * `--quackdb-uri` - QuackDB URI when `--repo` is omitted
    * `--quackdb-token` - QuackDB token
    * `--duckdb-database` - managed DuckDB database path when `--quackdb-uri` is omitted
    * `--duckdb-threads` - DuckDB execution threads
    * `--manifest-path` - sharded DuckDB manifest path
    * `--duckdb-memory-limit` - DuckDB memory limit per opened shard/server
    * `--shard-pool-size` - DB connections per shard when opening a manifest
    * `--shard-port-base` - first local QuackDB port when opening a sharded manifest
    * `--limit` - maximum findings to print (default: 100)
    * `--candidate-batch-size` - fragment candidate page size (default: 1000)
    * `--max-anchor-candidates` - skip patterns whose best anchor is broader than this (default: 10000)
    * `--json` - print JSON
  """

  use Mix.Task

  @shortdoc "Audits Reach source-pattern smells against an Exograph index"

  @impl true
  def run(args) do
    Mix.Task.run("app.start")

    {opts, modules, invalid} =
      OptionParser.parse(args,
        strict: [
          repo: :string,
          prefix: :string,
          quackdb_uri: :string,
          quackdb_token: :string,
          duckdb_database: :string,
          duckdb_threads: :integer,
          manifest_path: :string,
          duckdb_memory_limit: :string,
          shard_pool_size: :integer,
          shard_port_base: :integer,
          limit: :integer,
          candidate_batch_size: :integer,
          max_anchor_candidates: :integer,
          json: :boolean
        ],
        aliases: [n: :limit]
      )

    if invalid != [] do
      Mix.raise("Invalid options: #{inspect(invalid)}")
    end

    if modules == [] do
      Mix.raise("Expected at least one Reach smell module name")
    end

    index = open_index!(opts)
    smell_modules = Enum.map(modules, &module!/1)

    {:ok, result} =
      Exograph.Reach.SourceSmellAudit.scan(index, smell_modules,
        limit: Keyword.get(opts, :limit, 100),
        candidate_batch_size: Keyword.get(opts, :candidate_batch_size, 1_000),
        max_anchor_candidates: Keyword.get(opts, :max_anchor_candidates, 10_000)
      )

    print_result(result, opts)
  end

  defp open_index!(opts) do
    if manifest_path = Keyword.get(opts, :manifest_path) do
      {:ok, index} =
        Exograph.open_sharded(manifest_path,
          duckdb_threads: Keyword.get(opts, :duckdb_threads),
          duckdb_memory_limit: Keyword.get(opts, :duckdb_memory_limit),
          pool_size: Keyword.get(opts, :shard_pool_size),
          port_base: Keyword.get(opts, :shard_port_base, 9_700)
        )

      index
    else
      index_opts =
        opts
        |> Mix.Exograph.DuckDBOptions.opts()
        |> Keyword.put(:migrate?, false)

      {:ok, index} = Exograph.index([], index_opts)
      index
    end
  end

  defp print_result(result, opts) do
    if Keyword.get(opts, :json, false) do
      Mix.shell().info(JSON.encode!(result_json(result)))
    else
      Mix.shell().info(
        "#{length(result.findings)} finding(s), #{result.candidate_count} candidate(s), " <>
          "#{result.scanned_patterns} pattern(s), #{result.elapsed_ms}ms"
      )

      if result.skipped_patterns != [] do
        Mix.shell().info(
          "#{length(result.skipped_patterns)} pattern(s) skipped by anchor threshold"
        )
      end

      Enum.each(result.findings, &print_finding/1)
    end
  end

  defp print_finding(finding) do
    Mix.shell().info([
      inspect(finding.kind),
      " ",
      finding.file || "<unknown>",
      ":",
      to_string(finding.line || 0),
      " ",
      inspect(finding.check),
      "\n  ",
      finding.message
    ])

    if finding.snippet do
      Mix.shell().info("\n" <> indent(finding.snippet) <> "\n")
    end
  end

  defp result_json(result) do
    %{
      elapsed_ms: result.elapsed_ms,
      candidate_count: result.candidate_count,
      scanned_patterns: result.scanned_patterns,
      skipped_patterns: length(result.skipped_patterns),
      findings: Enum.map(result.findings, &finding_json/1)
    }
  end

  defp finding_json(finding) do
    %{
      check: inspect(finding.check),
      kind: finding.kind,
      message: finding.message,
      package_version: finding.package_version,
      file: finding.file,
      line: finding.line,
      snippet: finding.snippet,
      anchor_term: finding.anchor_term
    }
  end

  defp indent(text) do
    text
    |> String.split("\n")
    |> Enum.map_join("\n", &["  ", &1])
  end

  defp module!(name) do
    name
    |> String.split(".")
    |> Module.concat()
  end
end
